"""
Email dispatcher for sending language-aware, topic-filtered reports to subscribers.

This module handles the batch dispatch of markdown reports to subscribers
based on their city, topic, and language preferences. Unlike the email_sender.py
node (which is part of the pipeline chain), this dispatcher is called after all
pipelines complete and works with the cached reports dictionary.

Each subscriber receives a personalized email in their preferred language,
containing only the reports matching their selected topics.
"""

import time
import uuid
import queue
import logging
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timezone
from typing import Any

from utils.supabase_client import (
    get_all_subscribers_with_cities_and_topics,
    get_subscriber_referral_code,
    set_subscriber_referral_code,
)
from utils.report.translator import LANG_MAP
from utils.email.smtp import SMTPConnectionPool, send_single_email, is_email_configured
from utils.email.templates import convert_markdown_to_html, render_template
from utils.email.components import (
    build_social_share_urls,
    build_all_topic_sections_html,
    build_table_of_contents_html,
)
from pipelines.node.email_subscriber_content import (
    build_subscriber_topic_reports,
    build_translated_subscriber_topic_reports,
    save_failures,
)

logger = logging.getLogger(__name__)


def dispatch_emails_to_subscribers(
    reports: dict[str, dict[str, str]],
    translations: dict[str, dict[str, dict[str, str]]] | None = None,
) -> dict[str, Any]:
    """
    Query all subscribers and send each a personalized report in their preferred language.

    This function:
    1. Validates that reports is not empty
    2. Queries subscribers with their city, topic, and language preferences
    3. For each subscriber, selects the report in their preferred language:
       - English (or NULL): sends the original English report
       - Spanish/French: sends the translated version if available, falls back to English
    4. Combines matching topic reports into a single personalized email
    5. Tracks delivery statistics and failures

    Args:
        reports: Nested dictionary mapping city -> topic -> markdown report.
                 Generated from report_cache.get_all().
        translations: Optional nested dict mapping city -> topic -> lang -> translated markdown.
                      Generated by report_translator.translate_all_reports().

    Returns:
        Dictionary with delivery statistics.
    """

    # Check if email is configured
    if not is_email_configured():
        logger.info("Email configuration incomplete; skipping email dispatch")
        return {
            "total_sent": 0,
            "by_city": {},
            "missing_reports": [],
            "delivery_failures": [
                "Email not configured - missing SMTP_EMAIL or SMTP_APP_PASSWORD"
            ],
        }

    # Validate input
    if not reports:
        logger.warning("No reports available for dispatch (reports is empty)")
        return {
            "total_sent": 0,
            "by_city": {},
            "missing_reports": [],
            "delivery_failures": ["No reports available for dispatch"],
        }

    # Query all subscribers with their city, topic, and language preferences
    try:
        subscribers = get_all_subscribers_with_cities_and_topics()
    except Exception as e:
        logger.error(f"Failed to query subscribers: {e}")
        return {
            "total_sent": 0,
            "by_city": {},
            "missing_reports": [],
            "delivery_failures": [f"Failed to query subscribers: {str(e)}"],
        }

    if not subscribers:
        logger.info("No subscribers found")
        return {
            "total_sent": 0,
            "by_city": {},
            "missing_reports": [],
            "delivery_failures": [],
        }

    logger.info(f"Dispatching topic-filtered reports to {len(subscribers)} subscriber(s)")

    # Build per-subscriber email content and track missing reports
    send_queue: list[dict[str, str]] = []
    missing_reports: list[dict] = []

    for subscriber in subscribers:
        contact = subscriber.get("contact")
        city = subscriber.get("city")
        topics = subscriber.get("topics", [])
        preferred_language = subscriber.get("preferred_language")

        if not contact or not city:
            logger.warning(f"Subscriber missing contact or city: {subscriber}")
            continue

        if not city.strip():
            logger.warning(f"Subscriber has empty city name: {subscriber}")
            continue

        city_reports = reports.get(city, {})

        if not city_reports:
            logger.warning(f"No reports available for city: {city}")
            missing_reports.append({
                "email": contact,
                "city": city,
                "topics": topics,
                "reason": "No reports available for city",
                "timestamp": datetime.now(timezone.utc).isoformat(),
            })
            continue

        if not topics:
            logger.warning(f"Subscriber {contact} has no topic preferences")
            missing_reports.append({
                "email": contact,
                "city": city,
                "topics": [],
                "reason": "No topic preferences set",
                "timestamp": datetime.now(timezone.utc).isoformat(),
            })
            continue

        # Determine which content to send based on preferred_language
        lang_code = LANG_MAP.get(preferred_language or "") if preferred_language else None

        if lang_code and translations:
            # Try to build translated content for the preferred language
            topic_reports = build_translated_subscriber_topic_reports(
                topics, city, lang_code, translations
            )
            if not topic_reports:
                # Fall back to English if translation is not available
                logger.info(
                    f"No {preferred_language} translation for {contact} ({city}); "
                    f"falling back to English"
                )
                topic_reports = build_subscriber_topic_reports(topics, city_reports)
        else:
            # English or no preference — use original reports
            topic_reports = build_subscriber_topic_reports(topics, city_reports)

        if not topic_reports:
            logger.warning(
                f"No matching topic reports for subscriber {contact} "
                f"(city={city}, topics={topics})"
            )
            missing_reports.append({
                "email": contact,
                "city": city,
                "topics": topics,
                "reason": "No reports match subscriber topics",
                "timestamp": datetime.now(timezone.utc).isoformat(),
            })
            continue

        # Resolve or generate referral code for this subscriber
        try:
            referral_code = get_subscriber_referral_code(contact)
            if not referral_code:
                referral_code = uuid.uuid4().hex[:8]
                set_subscriber_referral_code(contact, referral_code)
        except Exception as e:
            logger.warning(f"Could not resolve referral code for {contact}: {e}")
            referral_code = None

        # Convert to HTML topic sections and queue for sending
        topic_html_pairs = [(name, convert_markdown_to_html(md)) for name, md in topic_reports]
        topic_names = [name for name, _ in topic_reports]
        sections_html = build_all_topic_sections_html(topic_html_pairs, referral_code=referral_code, city=city)
        social_share_urls = build_social_share_urls(referral_code=referral_code)
        toc_html = build_table_of_contents_html(topic_names)

        intro = (
            f"Here\u2019s what {city}, the statehouse, and Washington actually did this "
            f"week \u2014 organized by topic, every claim cited."
        )

        html_body = render_template(
            "",
            topic_sections_html=sections_html,
            social_share_urls=social_share_urls,
            table_of_contents_html=toc_html,
            greeting="Good morning, New Voters.",
            intro=intro,
        )

        send_queue.append({
            "contact": contact,
            "city": city,
            "html_body": html_body,
        })

    if not send_queue:
        logger.info("No emails to send after topic filtering")
        return {
            "total_sent": 0,
            "by_city": {},
            "missing_reports": missing_reports,
            "delivery_failures": [],
        }

    # Set up email infrastructure
    try:
        pool = SMTPConnectionPool(pool_size=10)
    except RuntimeError as e:
        logger.error(f"Failed to initialize SMTP connection pool: {e}")
        return {
            "total_sent": 0,
            "by_city": {},
            "missing_reports": missing_reports,
            "delivery_failures": [f"SMTP pool initialization failed: {str(e)}"],
        }

    failures_queue: queue.Queue = queue.Queue()

    delivery_stats: dict[str, Any] = {
        "total_sent": 0,
        "by_city": {},
        "missing_reports": missing_reports,
        "delivery_failures": [],
    }

    with pool:
        # Send emails in waves to avoid rate limiting
        waves = [send_queue[i : i + 100] for i in range(0, len(send_queue), 100)]

        for wave in waves:
            with ThreadPoolExecutor(max_workers=10) as executor:
                futures = []
                for item in wave:
                    future = executor.submit(
                        send_single_email,
                        pool,
                        item["contact"],
                        f"Your {item['city']} brief \u2014 city, state, and Congress this week",
                        item["html_body"],
                        failures_queue,
                    )
                    futures.append((future, item))

                for future, item in futures:
                    success = future.result()
                    if success:
                        city = item["city"]
                        delivery_stats["by_city"][city] = (
                            delivery_stats["by_city"].get(city, 0) + 1
                        )
                        delivery_stats["total_sent"] += 1

            time.sleep(1)

    # Extract failures from queue
    delivery_failures = []
    while not failures_queue.empty():
        try:
            delivery_failures.append(failures_queue.get_nowait())
        except queue.Empty:
            break

    # Save all failures
    all_failures = delivery_failures + missing_reports
    save_failures(all_failures)

    delivery_stats["delivery_failures"] = delivery_failures

    logger.info(
        f"Email dispatch complete: {delivery_stats['total_sent']} sent, "
        f"{len(delivery_failures)} delivery failures, "
        f"{len(missing_reports)} missing reports"
    )

    return delivery_stats
